
server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profileservice
  datasource:
    url: "jdbc:mysql://localhost:3306/profile_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: nguyenthanhxuan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

